# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-02-25 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.IntegerField()),
                ('department_name', models.CharField(max_length=140)),
                ('metric', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='ServerUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('units', models.IntegerField()),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch.ServerDetails')),
            ],
        ),
    ]
