# Generated by Django 2.0 on 2018-02-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_serverdetails_serverusage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='server_desc',
        ),
    ]
