# Generated by Django 2.0.2 on 2018-02-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_delete_server_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverusage',
            name='units',
            field=models.IntegerField(max_length=100),
        ),
    ]
