# Generated by Django 2.0.2 on 2018-02-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0005_auto_20180225_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverusage',
            name='units',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
